import type { CalendarEntry, CalendarQuery, ImportPreview } from "../domain";
import { tokyoDateKey } from "./calendarUtils";

export const DEMO_CALENDAR_ENTRIES: CalendarEntry[] = [
  {
    id: "calendar-trace",
    externalSessionId: "019f-demo-trace",
    title: "TRACE 指标校正",
    lastActivityAt: "2026-08-09T12:10:00.000Z",
    lastCompletedTurnAt: "2026-08-09T12:10:00.000Z",
    completionState: "completed",
    sourceState: "archived",
    importState: "imported_current",
    analysisState: "ready",
    importedVersionCount: 1,
    snapshotCount: 1,
    latestConversationId: "conversation-b5",
    turnCount: 18,
    activeDayCount: 2,
    timeCoverage: "complete",
  },
  {
    id: "calendar-windows-evaluation",
    externalSessionId: "019f-demo-windows",
    title: "Windows 11 移植评估",
    lastActivityAt: "2026-08-10T01:40:00.000Z",
    lastCompletedTurnAt: "2026-08-10T01:40:00.000Z",
    completionState: "completed",
    sourceState: "active",
    importState: "imported_current",
    analysisState: "partial",
    importedVersionCount: 1,
    snapshotCount: 1,
    latestConversationId: "conversation-b5",
    turnCount: 27,
    timeCoverage: "complete",
  },
  {
    id: "calendar-windows-handoff",
    externalSessionId: "019f-demo-handoff",
    title: "Windows 交接包整理",
    lastActivityAt: "2026-08-11T08:25:00.000Z",
    lastCompletedTurnAt: "2026-08-11T08:25:00.000Z",
    completionState: "completed",
    sourceState: "archived",
    importState: "imported_current",
    analysisState: "ready",
    importedVersionCount: 2,
    snapshotCount: 2,
    latestConversationId: "conversation-b5",
    turnCount: 16,
    timeCoverage: "complete",
  },
  {
    id: "calendar-jsonl-time",
    externalSessionId: "019f-demo-jsonl",
    title: "JSONL 时间戳检验",
    lastActivityAt: "2026-08-12T00:45:00.000Z",
    lastCompletedTurnAt: "2026-08-12T00:45:00.000Z",
    completionState: "completed",
    sourceState: "active",
    importState: "imported_current",
    analysisState: "ready",
    importedVersionCount: 1,
    snapshotCount: 1,
    latestConversationId: "conversation-b5",
    turnCount: 12,
    activeDayCount: 1,
    timeCoverage: "complete",
  },
  {
    id: "calendar-plan",
    externalSessionId: "019f-demo-calendar",
    title: "对话日历方案",
    lastActivityAt: "2026-08-12T06:20:00.000Z",
    lastCompletedTurnAt: "2026-08-12T05:58:00.000Z",
    completionState: "in_progress_or_unknown",
    sourceState: "active",
    importState: "not_imported",
    analysisState: "none",
    importedVersionCount: 0,
    snapshotCount: 0,
    turnCount: 9,
    timeCoverage: "complete",
  },
  {
    id: "calendar-layout-audit",
    externalSessionId: "019f-demo-layout",
    title: "布局持久化复核",
    lastActivityAt: "2026-08-12T06:34:00.000Z",
    lastCompletedTurnAt: "2026-08-12T06:34:00.000Z",
    completionState: "completed",
    sourceState: "active",
    importState: "source_updated",
    analysisState: "ready",
    importedVersionCount: 1,
    snapshotCount: 1,
    latestConversationId: "conversation-b5",
    turnCount: 14,
    timeCoverage: "complete",
  },
  {
    id: "calendar-density",
    externalSessionId: "019f-demo-density",
    title: "语义密度显示规则",
    lastActivityAt: "2026-08-12T06:47:00.000Z",
    lastCompletedTurnAt: "2026-08-12T06:47:00.000Z",
    completionState: "completed",
    sourceState: "active",
    importState: "imported_current",
    analysisState: "failed",
    importedVersionCount: 1,
    snapshotCount: 0,
    latestConversationId: "conversation-b5",
    turnCount: 11,
    timeCoverage: "complete",
  },
  {
    id: "calendar-source-missing",
    externalSessionId: "019f-demo-missing",
    title: "归档会话索引",
    lastActivityAt: "2026-08-13T01:15:00.000Z",
    lastCompletedTurnAt: "2026-08-13T01:15:00.000Z",
    completionState: "completed",
    sourceState: "missing",
    importState: "not_imported",
    analysisState: "none",
    importedVersionCount: 0,
    snapshotCount: 0,
    turnCount: 6,
    timeCoverage: "partial",
  },
];

export const DEMO_UNDATED_CALENDAR_ENTRIES: CalendarEntry[] = [
  {
    id: "calendar-undated",
    title: "可见对话导出（无消息时间）",
    completionState: "undated",
    sourceState: "import_only",
    importState: "imported_current",
    analysisState: "none",
    importedVersionCount: 1,
    snapshotCount: 0,
    latestConversationId: "conversation-undated",
    turnCount: 36,
    timeCoverage: "none",
  },
];

export function queryDemoCalendar(query: CalendarQuery): CalendarEntry[] {
  return structuredClone(DEMO_CALENDAR_ENTRIES.filter((entry) => {
    const date = entry.lastActivityAt ? tokyoDateKey(entry.lastActivityAt) : undefined;
    return date !== undefined && date >= query.startDate && date < query.endDateExclusive;
  }));
}
export function demoImportPreview(entryId: string): ImportPreview {
  const entry = [...DEMO_CALENDAR_ENTRIES, ...DEMO_UNDATED_CALENDAR_ENTRIES]
    .find((item) => item.id === entryId);
  if (!entry) throw new Error("找不到演示会话");
  return {
    id: `preview-${entry.id}`,
    title: entry.title,
    sourceKind: "codex_jsonl",
    sourceFormat: "raw_rollout",
    externalSessionId: entry.externalSessionId,
    firstVisibleAt: entry.lastActivityAt,
    lastActivityAt: entry.lastActivityAt,
    lastCompletedTurnAt: entry.lastCompletedTurnAt,
    timeCoverage: entry.timeCoverage ?? "complete",
    messages: [
      { id: `${entry.id}-u1`, speaker: "user", turnOrdinal: 1, text: "请分析这段会话中的问题、方案与逻辑关系。" },
      { id: `${entry.id}-a1`, speaker: "assistant", phase: "final", turnOrdinal: 2, text: "这是本地预览的可见回复；浏览器演示不会调用模型。" },
    ],
    characterCount: 52,
    warnings: ["浏览器演示只呈现确定性本地预览，不会导入或分析。"],
  };
}
